#pragma once
#include <string>
//EVERY TIME YOU ADD A NEW CODE, BE SURE TO ADD TO STATUSLOGGER!!!!!!!!!!!
#define SUCCESS 0
#define SERIALCONNECTIONSUCCEEDED 1
#define SERIALCONNECTIONFAILED 2
#define SERIALOPENERROR 3
#define SERIALBAUDERROR 4
#define SERIALFLOWERROR 5
#define SERIALPARITYERROR 6
#define SERIALSTOPBITERROR 7
#define SERIALCHARSIZERROR 8

#define VIDEOINITSUCCEEDED 9
#define VIDEONODECKLINKFOUND 10
#define VIDEOSETCALLBACKFAILED 11
#define VIDEOSTARTSTREAMSFAILED 12
#define VIDEOENABLEINPUTFAILED 13
#define VIDEOINPUTCAUGHTEXCEPTION 14
#define RELEASEFONTEXCEPTION 15

#define HUDSHUTDOWNSUCCEED 16
#define VIDEOINTERFACESTOPPED 17

#define SERIALTIMEOUT 18

#define FAILOPENSETTINGSFILE 19

#define OPENSETTINGSFILESUCCEEDED 20


#define SERIALNOCOMINSETTINGS 21
#define SERIALNOBAUDINSETTINGS 22
#define SERIALNOBSIZEINSETTINGS 23
#define SERIALNOPARITYINSETTINGS 24
#define SERIALNOSTBITSINSETTINGS 25

#define VIDEONOCOCREATE 26
#define VIDEOCOMINITFAILED 27
#define DECKLINKDISCOVERYFAIL 28

#define HUDINITIALIZED 29

#define SERIALCLOSED 30
#define FAILEDCREATEHOMEFOLDER 31
#define FAILEDCREATESETTINGSFILE 32
#define FAILEDCREATEDATAFOLDER 33

#define INVALIDKML 34
