#ifndef GEODATACACHESETTINGS
#define GEODATACACHESETTINGS
#define HIGHDEFLOD 12
#define ANGLE_BELOW_HORIZON 5.0 //FOR STARTERS
#define TILESIZE 0.08 //degrees? to start with
#define LOADCOMPLETEGRID

#define MAX_LENGTH 1024
#define LAYERLISTSIZE 14

#define LOD 9
#define FULLGRID false
#define ZOOMLEVELBASE 14
#define BUMPYGRIDSIZE 8

#endif // GEODATACACHESETTINGS
